EXERCISE SET 1

In [35]:
import numpy as np
import pandas as pd

Exercise 1 starts

In [28]:
# list of 15 ones
list_of_15_ones = []

for x in range(15):
    list_of_15_ones.append(1)

list_of_15_ones
#len(list_of_15_ones)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [29]:
# list of 15 number 7's
list_of_15_sevens = []

for x in range(15):
    list_of_15_sevens.append(7)

list_of_15_sevens

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

In [30]:
# list of numbers from 100 to 150
list_of_100_to_150 = []

for num in range(100, 151):
    list_of_100_to_150.append(num)

list_of_100_to_150

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150]

In [31]:
# list of even numbers between 0 and 100
even_nums_between_0_and_100 = []

for num in range (0, 101):
    if num % 2 == 0:
        even_nums_between_0_and_100.append(num)

even_nums_between_0_and_100

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [32]:
# list of years that are divisible by 4 between 1950 and 2020
list_of_years_etc = []

for num in range (1950, 2021):
    if num % 4 == 0:
        list_of_years_etc.append(num)

list_of_years_etc

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

Exercise 1 ends

Exercise 2 starts

In [38]:

# array of 15 zeroes with np
array_15_zeroes = np.zeros(15)

array_15_zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# array of 15 ones with np
array_15_ones = np.ones(15)

array_15_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
# array of 15 sevens with np
array_15_sevens = np.repeat(7, 15) # 7 what we want to repeat, 15 how many times.

array_15_sevens


array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [44]:
# array of numbers from 100 to 150 with np
array_from_100_to_150 = np.arange(100, 151) # like py range func but returns array

array_from_100_to_150


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [45]:
# array of numbers from 1900 to 2021 with np
array_from_1900_to_2021 = np.arange(1900, 2022)

array_from_1900_to_2021

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [46]:
# array of even nums between 0 and 100 with np
array_of_even_nums_between_0_and_100 = np.arange(0, 101, 2) # the step (2) defines the interval between each val in the array. so in this case it skips every other value. default stepsize is 1

array_of_even_nums_between_0_and_100

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [47]:
# array of years that are divisible by 4 between 1950 and 2020 with np

array_of_nums_divisible_by_4_between_1950_and_2020 = np.arange(1952, 2021, 4) # expert knowledge here that 1950 isn't divisible by 4 and 1952 is :D

array_of_nums_divisible_by_4_between_1950_and_2020


array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

Comparing python and NumPy, not much of a difference. NumPy = faster so personally liking it more.

Exercise 2 ends

Exercise 3 starts

In [49]:
# np vector containing values: 5, 16, 9, 2, 19, 18, 11, 7. use argmax() to find the position index of the largest value in the vector

given_nums = [5, 16, 9, 2, 19, 18, 11, 7] # python list
convert_to_nmp = np.array(given_nums) # convert list to numpy array/vector

index_of_largest_num = np.argmax(convert_to_nmp) # find the index of the largest number
index_of_largest_num


4

In [52]:
# 7x7 matrix with values from 1 to 49

seven_x_seven_matrix = np.arange(1, 50).reshape(7, 7) # chain func, first get vals between 1 and 49 then convert/reshape it to 7x7 matrix

#seven_x_seven_matrix

# EXTRA, same task without numpy
number = 1
seven_x_seven_matrix_without_numpy = []
# nested loop, basically create rowlist in outside loop -> jump to inside loop (stop at 7 runs, creates the 7x7) -> add our starting number to the previously created rowlist -> br
# increment by 1 -> add our incremented number to the rowlist -> etc. until 7 runs -> create another rowlist -> etc. etc.
for num_index in range(7):
    seven_x_seven_matrix_without_numpy.append([]) # new list/row
    for num_index_2 in range(7):
        seven_x_seven_matrix_without_numpy[num_index].append(number) # add the starting number
        number += 1 # increment starting number by 1

seven_x_seven_matrix_without_numpy


[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [67]:
# 8x8 random number matrix, values between 0 and 5

eight_x_eight_matrix = np.random.randint(0, 6, (8, 8)) # (numbers between 0 and 5, (array/matrix size 8x8))

eight_x_eight_matrix

array([[0, 1, 3, 4, 2, 1, 1, 5],
       [5, 2, 4, 3, 2, 4, 5, 5],
       [2, 1, 2, 4, 5, 3, 2, 4],
       [2, 0, 5, 4, 1, 4, 5, 5],
       [2, 3, 5, 3, 2, 5, 3, 0],
       [2, 0, 0, 3, 5, 5, 4, 1],
       [2, 0, 1, 0, 5, 2, 3, 5],
       [4, 2, 5, 5, 2, 5, 2, 5]])

In [73]:
# 8x8 random number matrix, using standard normal distribution values (between -3 n' 3)

eight_x_eight_matrix_with_snd_values = np.random.randn(8, 8) # create the 8x8 matrix with standard normal distribution values, randn mean = 0 and deviation 1

eight_x_eight_matrix_with_snd_values

array([[-2.3244125 ,  1.43699097, -0.07997301, -0.93988983,  1.74745825,
        -0.71095095,  1.5105493 ,  1.31029821],
       [ 0.66413595, -1.08481076,  0.442351  , -0.23356707, -1.45415201,
         1.95604855,  0.31663491,  1.15021914],
       [-0.6681414 ,  0.09812036, -0.78683291,  2.53757987,  0.06007365,
        -0.32812889,  1.82315561, -0.60561469],
       [-0.389662  ,  0.58993786,  0.836054  , -0.28569993,  1.54170709,
        -1.61432352, -1.37880526, -0.14409237],
       [ 0.56292562,  0.7705753 ,  1.26579609,  0.01078566,  1.13078218,
         1.34541778,  1.21717063,  1.13392773],
       [ 0.20450937,  1.65897862,  0.57887238,  0.85108254, -0.73028815,
         0.25027997,  0.90252376,  2.42289341],
       [ 1.41142012,  0.22022241, -0.55983024,  0.38351565, -0.01038824,
        -0.43258452, -1.78093192,  1.27238872],
       [-0.28702527, -0.34820933, -0.3702499 , -1.22350345,  1.11615177,
        -0.05609414, -0.30137648, -0.15372729]])

Exercise 3 ends

Exercise 4 starts